### PR TITLE
copied skeleton code from existing sample

### PR DESCRIPTION
**Pull request by kalyankrishna1**
## Purpose

active-directory-dotnet-native-aspnetcore-v2\2. Web API now calls Microsoft Graph
proposed folder structure and updated .gitignore
* ...

## Does this introduce a breaking change?

```
[X ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ X] Other... Please describe:
Sets up new code base for the next sample

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code
<!-- Add steps to run the tests suite and/or manually test -->
```
```

## What to Check
Verify that the following are valid
* ...

## Other Information
<!-- Add any other helpful information that may be needed here. -->

### CODE REVIEW

**Comment by jmprieur** [comment]
@kalyankrishna1. I'm sure you realize, but preferred to check: we don't need/want the TodoListClient

**Comment by kalyankrishna1** [comment]
so we just want to cover how to protect an api? The issue I was trying to solve was unlike a web app, we cannot "show" a protected web api working unless there is a client app. For web apps, we can just ask to developer to try signing in after making the changes we request them to make to test their changes

---
In reply to: [495562335](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/104#issuecomment-495562335) [](ancestors = 495562335)

**Comment by kalyankrishna1** [comment]
Or can we consider sharing a client app across all WebAPI tutorials?

---
In reply to: [498203307](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/104#issuecomment-498203307) [](ancestors = 498203307,495562335)

**Comment by jmprieur** [comment]
We already have a tutorial for "protect an API" and "protected API calls downstream API", @kalyankrishna1 
Here we just want to have our Web App of this tutorial to that API of that tutorial unchanged, instead of calling Graph (no need to do something fancy on the Web App side)

**Comment by jackpanetta** [comment]
Hey guys, any idea when this sample will be updated? I'm looking for example code on how to perform an OBO Auth Request to my own custom API. Both client and service running .NET Core.

**Comment by kalyankrishna1** [comment]
I hope to be done by the end of this week. A vacation delayed things..

**Pull request merged**
