### PR TITLE
added package.json with specific versions as recommended by Git

### PR DESCRIPTION
**Pull request by aremo-ms**
## Purpose

Added package.json under every wwwroot/lib/bootstrap as recommended by GitHub automation

### CODE REVIEW

**Review by jmprieur — APPROVED** [review]
LGTM
Thanks @aremo-ms

**Comment by v-michaelmi** [comment]
Are you sure these are **dependencies** and not just **devDependencies**?

**Comment by aremo-ms** [comment]
> Are you sure these are **dependencies** and not just **devDependencies**?
> 
> Would **shell.js** be needed for a production build?

I just did what was suggested, And this is a sample
image

**Comment by v-michaelmi** [comment]
Ideally it wouldn't matter because you're right it is just a sample but it's good hygiene.

Looking at the bootstrap library referenced it seems that it is a **devDependency** and not a pure **dependency**.

image

**Comment by aremo-ms** [comment]
> Ideally it wouldn't matter because you're right it is just a sample but it's good hygiene.
> 
> Looking at the [bootstrap](https://www.npmjs.com/package/bootstrap) library referenced it seems that it is a **devDependency** and not a pure **dependency**.
> 
> image

I'm fine to fix it, but I don't see markdown-it dependency for bootstrap. Ideas?

**Comment by v-michaelmi** [comment]
Indeed.

Much more annoying is I'm not seeing that dependency in any of the other jQuery libraries neither. Not sure where that's coming from.

**Comment by v-michaelmi** [comment]
After giving it a second look it seems that dependabot is 'guessing' what those dependencies could be and is picking **markdown-it** as a possible library dependency but will need to confirm that. I'm not seeing anything here that uses that.

**Comment by aremo-ms** [comment]
> After giving it a second look it seems that dependabot is 'guessing' what those dependencies could be since the **package.json** file isn't there and is picking **markdown-it** as a possible library dependency. But I will need to confirm that. I'm not seeing anything here that uses that.

I'm changing both to devDependencies

**Comment by v-michaelmi** [comment]
@aremo-ms 

LGTM

**Review by v-michaelmi — APPROVED** [review]

**Pull request merged**
