### PR TITLE
Porduction

### PR DESCRIPTION
**Pull request by HanqingLuo**
# {PR title}

- [x] You've read the [Contributor Guide](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

{Detail}

Fixes #{bug number} (in this specific format)

### CODE REVIEW

**Comment by HanqingLuo** [comment]
@microsoft-github-policy-service agree [company="Cognex"]

**Comment by HanqingLuo** [comment]
@microsoft-github-policy-service agree

**Comment by HanqingLuo** [comment]
@microsoft-github-policy-service agree

**Comment by jennyf19** [comment]
can you give more context into this PR @HanqingLuo ?

**Comment by jmprieur** [comment]
Closing as it's probably an error

**Pull request closed without merging**
