### PR TITLE
Damienbod/update  2-WebApp-graph-user\2-1-Call-MSGraph

### PR DESCRIPTION
**Pull request by damienbod**
## Purpose

- Update bootstrap 4, frontend packages, css
- Update to latest Microsoft.Identity.Web C# templates
- Update app settings
- Update Nuget packages ASP.NET Core 3.1
- alignment with templates

issues: 
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/397

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by damienbod** [comment]
@jmprieur @pmaytak  Not sure who to address here. I updated the styles and bootstrap 4 using the latest ASP.NET Core 3.1 templates. Left the project as an ASP.NET Core MVC 3.1. Let me know if this is ok for you and if it's good like this. I can update the other projects in the 2-1-Call-MSGraph folder in separate PRs. (If it helps you.)

Greetings Damien

**Comment by pmaytak** [comment]
Thanks @damienbod for your work. I'll let others provide guidance.

**Comment by jmprieur** [comment]
I've 2 questions:
- If we take this PR shouldn't we do it for all the folders of this incremental tutorial?
- shouldn't we rather wait until .NET 5 GAs (as the .NET 5.0 templates from .NET 5 Preview 8 leverage Microsoft.Identity.Web)

**Comment by damienbod** [comment]
Hi @jmprieur I was planning to update one at a time, each in a separate PR. Once this is ok, I'll do the others.

With .NET 5, I think these examples should stay at 3.1 as this is LTS. .NET 5 will have templatesin Visual Studio as well. Updating 3.1 to .NET 5 is also easy for users. Most projects I know stick to the LTS versions, if possible. Just my 2 cents.

Thanks for the feedback.

Greetings Damien

**Comment by jmprieur** [comment]
Thanks for your quick feedback, @damienbod 
Don't you think we should rewrite the samples with the new Microsoft.Identity.Web templates (0.3.1-preview) ?

**Comment by damienbod** [comment]
Unsure about this. Most people use 3.1 at the moment. You want people to try this out, so the barrier is lower with 3.1. Maybe switch as week before .NET is released?

Also maybe move to Razor Pages? This could be done in a second step anyway. The bootstrap and UI changes are the same for all these options. Only the UI parts were changed in this PR.  We could do this in 2 steps:

- Update UI with ASP.NET Core as it is. (Just bootstrap 4, UI styles like the templates)
- Move to Razor Pages/.NET 5 or whatever you feel is best.

Greetings Damien

**Comment by jmprieur** [comment]
The 0.3.1 project templates (See https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-template) are both for .NET Core 3.1 and .NET 5.0. They are multi-target
just use `--framework netcoreapp3.1` to get netcore3.1 ones (we need to documented that, btw, @jennyf19, @pmaytak)

```Shell
-f|--framework                    The target framework for the project.
                                        net5.0           - Target net5.0
                                        netcoreapp3.1    - Target netcoreapp3.1
                                        netcoreapp3.0    - Target netcoreapp3.0
                                        netcoreapp2.1    - Target netcoreapp2.1
```

**Comment by mmacy** [comment]
@knicholasa some discussions around versioning in this PR for us to consider on docs.

**Comment by damienbod** [comment]
Hi @jmprieur thanks for you feedback, trying out the new templates. Just wondering, do I need to change anything in this PR, or it is good? The changes in this PR match the templates.

Greetings Damien

**Comment by damienbod** [comment]
@kalyankrishna1 @TiagoBrenck Is this PR ok for you?

Greetings Damien

**Comment by kalyankrishna1** [comment]
@damienbod we are awaiting some changes in the FW. We have this PR in our view. We'd accept after absorbing other changes in a few weeks. thanks for your patience

**Review by jmprieur — APPROVED** [review]
LGTM.
Thanks @damienbod

**Pull request merged**
